# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from driver import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 796)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_pitchRate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pitchRate.sizePolicy().hasHeightForWidth())
        self.pushButton_pitchRate.setSizePolicy(sizePolicy)
        self.pushButton_pitchRate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_pitchRate.setFont(font)
        self.pushButton_pitchRate.setAutoDefault(False)
        self.pushButton_pitchRate.setDefault(False)
        self.pushButton_pitchRate.setFlat(False)
        self.pushButton_pitchRate.setObjectName("pushButton_pitchRate")
        self.verticalLayout_4.addWidget(self.pushButton_pitchRate)
        self.label_pitchRate = QtWidgets.QLabel(self.centralwidget)
        self.label_pitchRate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchRate.setObjectName("label_pitchRate")
        self.verticalLayout_4.addWidget(self.label_pitchRate)
        self.label_pitchRateValue = QtWidgets.QLabel(self.centralwidget)
        self.label_pitchRateValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_pitchRateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchRateValue.setObjectName("label_pitchRateValue")
        self.verticalLayout_4.addWidget(self.label_pitchRateValue)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.pushButton_rollRate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rollRate.sizePolicy().hasHeightForWidth())
        self.pushButton_rollRate.setSizePolicy(sizePolicy)
        self.pushButton_rollRate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_rollRate.setFont(font)
        self.pushButton_rollRate.setCheckable(False)
        self.pushButton_rollRate.setChecked(False)
        self.pushButton_rollRate.setAutoDefault(False)
        self.pushButton_rollRate.setDefault(False)
        self.pushButton_rollRate.setFlat(False)
        self.pushButton_rollRate.setObjectName("pushButton_rollRate")
        self.verticalLayout_5.addWidget(self.pushButton_rollRate)
        self.label_rollRate = QtWidgets.QLabel(self.centralwidget)
        self.label_rollRate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_rollRate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_rollRate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rollRate.setObjectName("label_rollRate")
        self.verticalLayout_5.addWidget(self.label_rollRate)
        self.label_rollRateValue = QtWidgets.QLabel(self.centralwidget)
        self.label_rollRateValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rollRateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rollRateValue.setObjectName("label_rollRateValue")
        self.verticalLayout_5.addWidget(self.label_rollRateValue)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem7)
        self.pushButton_yawRate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yawRate.sizePolicy().hasHeightForWidth())
        self.pushButton_yawRate.setSizePolicy(sizePolicy)
        self.pushButton_yawRate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_yawRate.setFont(font)
        self.pushButton_yawRate.setAutoDefault(False)
        self.pushButton_yawRate.setDefault(False)
        self.pushButton_yawRate.setFlat(False)
        self.pushButton_yawRate.setObjectName("pushButton_yawRate")
        self.verticalLayout_6.addWidget(self.pushButton_yawRate)
        self.label_yawRate = QtWidgets.QLabel(self.centralwidget)
        self.label_yawRate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yawRate.setObjectName("label_yawRate")
        self.verticalLayout_6.addWidget(self.label_yawRate)
        self.label_yawRateValue = QtWidgets.QLabel(self.centralwidget)
        self.label_yawRateValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_yawRateValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yawRateValue.setObjectName("label_yawRateValue")
        self.verticalLayout_6.addWidget(self.label_yawRateValue)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem11)
        self.pushButton_elevatorPosition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_elevatorPosition.sizePolicy().hasHeightForWidth())
        self.pushButton_elevatorPosition.setSizePolicy(sizePolicy)
        self.pushButton_elevatorPosition.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_elevatorPosition.setFont(font)
        self.pushButton_elevatorPosition.setAutoDefault(False)
        self.pushButton_elevatorPosition.setDefault(False)
        self.pushButton_elevatorPosition.setFlat(False)
        self.pushButton_elevatorPosition.setObjectName("pushButton_elevatorPosition")
        self.verticalLayout.addWidget(self.pushButton_elevatorPosition)
        self.label_elevatorPosition = QtWidgets.QLabel(self.centralwidget)
        self.label_elevatorPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_elevatorPosition.setObjectName("label_elevatorPosition")
        self.verticalLayout.addWidget(self.label_elevatorPosition)
        self.label_elevatorPositionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_elevatorPositionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_elevatorPositionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_elevatorPositionValue.setObjectName("label_elevatorPositionValue")
        self.verticalLayout.addWidget(self.label_elevatorPositionValue)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem13 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem14)
        self.pushButton_aileronPosition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_aileronPosition.sizePolicy().hasHeightForWidth())
        self.pushButton_aileronPosition.setSizePolicy(sizePolicy)
        self.pushButton_aileronPosition.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_aileronPosition.setFont(font)
        self.pushButton_aileronPosition.setAutoDefault(False)
        self.pushButton_aileronPosition.setDefault(False)
        self.pushButton_aileronPosition.setFlat(False)
        self.pushButton_aileronPosition.setObjectName("pushButton_aileronPosition")
        self.verticalLayout_2.addWidget(self.pushButton_aileronPosition)
        self.label_aileronPosition = QtWidgets.QLabel(self.centralwidget)
        self.label_aileronPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aileronPosition.setObjectName("label_aileronPosition")
        self.verticalLayout_2.addWidget(self.label_aileronPosition)
        self.label_aileronPositionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_aileronPositionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_aileronPositionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_aileronPositionValue.setObjectName("label_aileronPositionValue")
        self.verticalLayout_2.addWidget(self.label_aileronPositionValue)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem16 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem17)
        self.pushButton_rudderPosition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rudderPosition.sizePolicy().hasHeightForWidth())
        self.pushButton_rudderPosition.setSizePolicy(sizePolicy)
        self.pushButton_rudderPosition.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_rudderPosition.setFont(font)
        self.pushButton_rudderPosition.setAutoDefault(False)
        self.pushButton_rudderPosition.setDefault(False)
        self.pushButton_rudderPosition.setFlat(False)
        self.pushButton_rudderPosition.setObjectName("pushButton_rudderPosition")
        self.verticalLayout_3.addWidget(self.pushButton_rudderPosition)
        self.label_rudderPosition = QtWidgets.QLabel(self.centralwidget)
        self.label_rudderPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rudderPosition.setObjectName("label_rudderPosition")
        self.verticalLayout_3.addWidget(self.label_rudderPosition)
        self.label_rudderPositionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_rudderPositionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rudderPositionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rudderPositionValue.setObjectName("label_rudderPositionValue")
        self.verticalLayout_3.addWidget(self.label_rudderPositionValue)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem19 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem20, 5, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem21 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem21)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem22)
        self.pushButton_pitchDeflection = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pitchDeflection.sizePolicy().hasHeightForWidth())
        self.pushButton_pitchDeflection.setSizePolicy(sizePolicy)
        self.pushButton_pitchDeflection.setMinimumSize(QtCore.QSize(135, 65))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_pitchDeflection.setFont(font)
        self.pushButton_pitchDeflection.setAutoDefault(False)
        self.pushButton_pitchDeflection.setDefault(False)
        self.pushButton_pitchDeflection.setFlat(False)
        self.pushButton_pitchDeflection.setObjectName("pushButton_pitchDeflection")
        self.verticalLayout_8.addWidget(self.pushButton_pitchDeflection)
        self.label_pitchDeflection = QtWidgets.QLabel(self.centralwidget)
        self.label_pitchDeflection.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchDeflection.setObjectName("label_pitchDeflection")
        self.verticalLayout_8.addWidget(self.label_pitchDeflection)
        self.label_pitchDeflectionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_pitchDeflectionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_pitchDeflectionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchDeflectionValue.setObjectName("label_pitchDeflectionValue")
        self.verticalLayout_8.addWidget(self.label_pitchDeflectionValue)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem23)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem24 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem24)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem25)
        self.pushButton_rollDeflection = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rollDeflection.sizePolicy().hasHeightForWidth())
        self.pushButton_rollDeflection.setSizePolicy(sizePolicy)
        self.pushButton_rollDeflection.setMinimumSize(QtCore.QSize(135, 65))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_rollDeflection.setFont(font)
        self.pushButton_rollDeflection.setAutoDefault(False)
        self.pushButton_rollDeflection.setDefault(False)
        self.pushButton_rollDeflection.setFlat(False)
        self.pushButton_rollDeflection.setObjectName("pushButton_rollDeflection")
        self.verticalLayout_9.addWidget(self.pushButton_rollDeflection)
        self.label_rollDeflection = QtWidgets.QLabel(self.centralwidget)
        self.label_rollDeflection.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rollDeflection.setObjectName("label_rollDeflection")
        self.verticalLayout_9.addWidget(self.label_rollDeflection)
        self.label_rollDeflectionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_rollDeflectionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_rollDeflectionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rollDeflectionValue.setObjectName("label_rollDeflectionValue")
        self.verticalLayout_9.addWidget(self.label_rollDeflectionValue)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem26)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        spacerItem27 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem27)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem28)
        self.pushButton_yawDeflection = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yawDeflection.sizePolicy().hasHeightForWidth())
        self.pushButton_yawDeflection.setSizePolicy(sizePolicy)
        self.pushButton_yawDeflection.setMinimumSize(QtCore.QSize(135, 65))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(True)
        self.pushButton_yawDeflection.setFont(font)
        self.pushButton_yawDeflection.setAutoDefault(False)
        self.pushButton_yawDeflection.setDefault(False)
        self.pushButton_yawDeflection.setFlat(False)
        self.pushButton_yawDeflection.setObjectName("pushButton_yawDeflection")
        self.verticalLayout_7.addWidget(self.pushButton_yawDeflection)
        self.label_yawDeflection = QtWidgets.QLabel(self.centralwidget)
        self.label_yawDeflection.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yawDeflection.setObjectName("label_yawDeflection")
        self.verticalLayout_7.addWidget(self.label_yawDeflection)
        self.label_yawDeflectionValue = QtWidgets.QLabel(self.centralwidget)
        self.label_yawDeflectionValue.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_yawDeflectionValue.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yawDeflectionValue.setObjectName("label_yawDeflectionValue")
        self.verticalLayout_7.addWidget(self.label_yawDeflectionValue)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem29)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem30 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem30)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_infoBar_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infoBar_status.sizePolicy().hasHeightForWidth())
        self.label_infoBar_status.setSizePolicy(sizePolicy)
        self.label_infoBar_status.setMinimumSize(QtCore.QSize(95, 0))
        self.label_infoBar_status.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_status.setObjectName("label_infoBar_status")
        self.horizontalLayout_5.addWidget(self.label_infoBar_status)
        spacerItem31 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem31)
        self.label_infoBar_limits = QtWidgets.QLabel(self.centralwidget)
        self.label_infoBar_limits.setMinimumSize(QtCore.QSize(145, 0))
        self.label_infoBar_limits.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_limits.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_limits.setObjectName("label_infoBar_limits")
        self.horizontalLayout_5.addWidget(self.label_infoBar_limits)
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem32)
        self.label_infoBar_output = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infoBar_output.sizePolicy().hasHeightForWidth())
        self.label_infoBar_output.setSizePolicy(sizePolicy)
        self.label_infoBar_output.setMinimumSize(QtCore.QSize(825, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_infoBar_output.setFont(font)
        self.label_infoBar_output.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_output.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_output.setScaledContents(False)
        self.label_infoBar_output.setObjectName("label_infoBar_output")
        self.horizontalLayout_5.addWidget(self.label_infoBar_output)
        spacerItem33 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem33)
        self.label_infoBar_startTime = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infoBar_startTime.sizePolicy().hasHeightForWidth())
        self.label_infoBar_startTime.setSizePolicy(sizePolicy)
        self.label_infoBar_startTime.setMinimumSize(QtCore.QSize(135, 0))
        self.label_infoBar_startTime.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_startTime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_startTime.setObjectName("label_infoBar_startTime")
        self.horizontalLayout_5.addWidget(self.label_infoBar_startTime)
        spacerItem34 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem34)
        self.label_infoBar_elapsedTime = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infoBar_elapsedTime.sizePolicy().hasHeightForWidth())
        self.label_infoBar_elapsedTime.setSizePolicy(sizePolicy)
        self.label_infoBar_elapsedTime.setMinimumSize(QtCore.QSize(150, 0))
        self.label_infoBar_elapsedTime.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_elapsedTime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_elapsedTime.setObjectName("label_infoBar_elapsedTime")
        self.horizontalLayout_5.addWidget(self.label_infoBar_elapsedTime)
        spacerItem35 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem35)
        self.label_infoBar_PCCTime = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infoBar_PCCTime.sizePolicy().hasHeightForWidth())
        self.label_infoBar_PCCTime.setSizePolicy(sizePolicy)
        self.label_infoBar_PCCTime.setMinimumSize(QtCore.QSize(130, 0))
        self.label_infoBar_PCCTime.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_infoBar_PCCTime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_infoBar_PCCTime.setObjectName("label_infoBar_PCCTime")
        self.horizontalLayout_5.addWidget(self.label_infoBar_PCCTime)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem36, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_toolBar_PCCFile = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_toolBar_PCCFile.sizePolicy().hasHeightForWidth())
        self.label_toolBar_PCCFile.setSizePolicy(sizePolicy)
        self.label_toolBar_PCCFile.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_toolBar_PCCFile.setFont(font)
        self.label_toolBar_PCCFile.setFrameShape(QtWidgets.QFrame.Box)
        self.label_toolBar_PCCFile.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_toolBar_PCCFile.setScaledContents(False)
        self.label_toolBar_PCCFile.setObjectName("label_toolBar_PCCFile")
        self.horizontalLayout.addWidget(self.label_toolBar_PCCFile)
        self.pushButton_tooBar_flag = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tooBar_flag.sizePolicy().hasHeightForWidth())
        self.pushButton_tooBar_flag.setSizePolicy(sizePolicy)
        self.pushButton_tooBar_flag.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_tooBar_flag.setCheckable(True)
        self.pushButton_tooBar_flag.setObjectName("pushButton_tooBar_flag")
        self.horizontalLayout.addWidget(self.pushButton_tooBar_flag)
        self.pushButton_toolBar_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toolBar_start.setDefault(True)
        self.pushButton_toolBar_start.setObjectName("pushButton_toolBar_start")
        self.horizontalLayout.addWidget(self.pushButton_toolBar_start)
        self.pushButton_toolBar_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toolBar_stop.setObjectName("pushButton_toolBar_stop")
        self.horizontalLayout.addWidget(self.pushButton_toolBar_stop)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLog = QtWidgets.QMenu(self.menubar)
        self.menuLog.setObjectName("menuLog")
        self.menuLimits = QtWidgets.QMenu(self.menubar)
        self.menuLimits.setObjectName("menuLimits")
        self.menuTrack_Position_Rate_Limits = QtWidgets.QMenu(self.menuLimits)
        self.menuTrack_Position_Rate_Limits.setObjectName("menuTrack_Position_Rate_Limits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_PCC_Telemetry_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_PCC_Telemetry_File.setObjectName("actionOpen_PCC_Telemetry_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Existing_Output_Log = QtWidgets.QAction(MainWindow)
        self.actionOpen_Existing_Output_Log.setObjectName("actionOpen_Existing_Output_Log")
        self.actionNew_Output_Log_File = QtWidgets.QAction(MainWindow)
        self.actionNew_Output_Log_File.setObjectName("actionNew_Output_Log_File")
        self.actionDefine_Manual_Limts = QtWidgets.QAction(MainWindow)
        self.actionDefine_Manual_Limts.setObjectName("actionDefine_Manual_Limts")
        self.actionOn = QtWidgets.QAction(MainWindow)
        self.actionOn.setCheckable(True)
        self.actionOn.setObjectName("actionOn")
        self.actionOff = QtWidgets.QAction(MainWindow)
        self.actionOff.setCheckable(True)
        self.actionOff.setChecked(True)
        self.actionOff.setObjectName("actionOff")
        self.menuFile.addAction(self.actionOpen_PCC_Telemetry_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuLog.addAction(self.actionOpen_Existing_Output_Log)
        self.menuLog.addAction(self.actionNew_Output_Log_File)
        self.menuTrack_Position_Rate_Limits.addAction(self.actionOn)
        self.menuTrack_Position_Rate_Limits.addAction(self.actionOff)
        self.menuLimits.addAction(self.actionDefine_Manual_Limts)
        self.menuLimits.addAction(self.menuTrack_Position_Rate_Limits.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuLog.menuAction())
        self.menubar.addAction(self.menuLimits.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_toolBar_stop.clicked.connect(MainWindow.close)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionOff.triggered['bool'].connect(self.actionOn.toggle)
        self.actionOn.triggered['bool'].connect(self.actionOff.toggle)
        self.actionOpen_PCC_Telemetry_File.triggered.connect(self.connector_openPCCTelemetryFile)
        self.actionDefine_Manual_Limts.triggered.connect(self.connector_openLimitsDialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raspet Flight Display"))
        self.pushButton_pitchRate.setText(_translate("MainWindow", "Normal"))
        self.label_pitchRate.setText(_translate("MainWindow", "Pitch Rate (deg/s)"))
        self.label_pitchRateValue.setText(_translate("MainWindow", "null"))
        self.pushButton_rollRate.setText(_translate("MainWindow", "Normal"))
        self.label_rollRate.setText(_translate("MainWindow", "Roll Rate (deg/s)"))
        self.label_rollRateValue.setText(_translate("MainWindow", "null"))
        self.pushButton_yawRate.setText(_translate("MainWindow", "Normal"))
        self.label_yawRate.setText(_translate("MainWindow", "Yaw Rate (deg/s)"))
        self.label_yawRateValue.setText(_translate("MainWindow", "null"))
        self.pushButton_elevatorPosition.setText(_translate("MainWindow", "Normal"))
        self.label_elevatorPosition.setText(_translate("MainWindow", "Elevator Pos. (deg)"))
        self.label_elevatorPositionValue.setText(_translate("MainWindow", "null"))
        self.pushButton_aileronPosition.setText(_translate("MainWindow", "Normal"))
        self.label_aileronPosition.setText(_translate("MainWindow", "Aileron Pos. (deg)"))
        self.label_aileronPositionValue.setText(_translate("MainWindow", "null"))
        self.pushButton_rudderPosition.setText(_translate("MainWindow", "Normal"))
        self.label_rudderPosition.setText(_translate("MainWindow", "Rudder Pos. (deg)"))
        self.label_rudderPositionValue.setText(_translate("MainWindow", "null"))
        self.pushButton_pitchDeflection.setText(_translate("MainWindow", "Normal"))
        self.label_pitchDeflection.setText(_translate("MainWindow", "Pitch Deflection"))
        self.label_pitchDeflectionValue.setText(_translate("MainWindow", "null"))
        self.pushButton_rollDeflection.setText(_translate("MainWindow", "Normal"))
        self.label_rollDeflection.setText(_translate("MainWindow", "Roll Deflection"))
        self.label_rollDeflectionValue.setText(_translate("MainWindow", "null"))
        self.pushButton_yawDeflection.setText(_translate("MainWindow", "Normal"))
        self.label_yawDeflection.setText(_translate("MainWindow", "Yaw Deflection"))
        self.label_yawDeflectionValue.setText(_translate("MainWindow", "null"))
        self.label_infoBar_status.setText(_translate("MainWindow", "Status: Idle"))
        self.label_infoBar_limits.setText(_translate("MainWindow", "Manual Limits: Off"))
        self.label_infoBar_output.setText(_translate("MainWindow", "Output Log: Off"))
        self.label_infoBar_startTime.setText(_translate("MainWindow", "Start Time: 00:00:00"))
        self.label_infoBar_elapsedTime.setText(_translate("MainWindow", "Elapsed Time: 00:00:00"))
        self.label_infoBar_PCCTime.setText(_translate("MainWindow", "PCC Time: 00:00:00"))
        self.label_toolBar_PCCFile.setText(_translate("MainWindow", "PCC Telemetry File: N/A"))
        self.pushButton_tooBar_flag.setText(_translate("MainWindow", "Flag"))
        self.pushButton_toolBar_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_toolBar_stop.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLog.setTitle(_translate("MainWindow", "Log"))
        self.menuLimits.setTitle(_translate("MainWindow", "Limits"))
        self.menuTrack_Position_Rate_Limits.setTitle(_translate("MainWindow", "Track Manual Limits"))
        self.actionOpen_PCC_Telemetry_File.setText(_translate("MainWindow", "Open PCC Telemetry File..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_Existing_Output_Log.setText(_translate("MainWindow", "Open Existing Output Log File..."))
        self.actionNew_Output_Log_File.setText(_translate("MainWindow", "New Output Log File"))
        self.actionDefine_Manual_Limts.setText(_translate("MainWindow", "Manually Define Limts"))
        self.actionOn.setText(_translate("MainWindow", "On"))
        self.actionOff.setText(_translate("MainWindow", "Off"))

    def connector_openPCCTelemetryFile(self):
        openPCCTelemetryFile(self)

    def connector_openLimitsDialog(self):
        openLimitsDialog(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
